h=int(input("Ingrese la hora"))
m=int(input("Ingrese los minutos"))
s=int(input("Ingrese los segundos"))
s= (s+(h*3600)+(m*60))
h2=int(input("Ingrese la hora2"))
m2=int(input("Ingrese los minutos2"))
s2=int(input("Ingrese los segundos2"))
s2= (s2+(h2*3600)+(m2*60))
sf=s-s2
print(sf)